services:

    typecho_server:
        container_name: 'typecho-server'
        image: 'joyqi/typecho:nightly-php8.2-apache'
        ports:
            - '8001:80'
        volumes:
            - './:/app'
        networks:
            - default

    mysql_server:
        container_name: 'mysql-service'
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-service:/var/lib/mysql'
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
        networks:
            - default

networks:
    default:
        driver: bridge

volumes:
    mysql-service:
        driver: local